### ISSUE TITLE
qgis 3 fail due to time.clock deprecation in python 3.8

### ISSUE THREAD

**Issue by fiftysevendegreesofrad** [fiftysevendegreesofrad/sdna_open#9]
ERR: File "D:\Program Files (x86)\sDNA\bin\sdnaintegral.py", line 4, in <module>
ERR: commandline_integral_prepare("sdnaintegral")
ERR: File "D:\Program Files (x86)\sDNA\commandline_integral_prepare.py", line 98, in commandline_integral_prepare
ERR: runcalculation(env,
ERR: File "D:\Program Files (x86)\sDNA\runcalculation.py", line 151, in runcalculation
ERR: st = time.clock()
ERR: AttributeError: module 'time' has no attribute 'clock'
ERR: Exception ignored in: <function Writer.__del__ at 0x0000014B4638B0D0>
ERR: Traceback (most recent call last):
ERR: File "D:\Program Files (x86)\sDNA\shapefile.py", line 1104, in __del__
ERR: self.close()
ERR: File "D:\Program Files (x86)\sDNA\shapefile.py", line 1125, in close
ERR: self.__shapefileHeader(self.shp, headerType='shp')
ERR: File "D:\Program Files (x86)\sDNA\shapefile.py", line 1299, in __shapefileHeader
ERR: f.write(pack("<4d", zbox[0], zbox[1], mbox[0], mbox[1]))
ERR: TypeError: 'NoneType' object is not subscriptable
External command completed
Execution completed in 0.79 seconds
Results:
{'OUTPUT': <sdna.sdna_plugin_algorithm.ShapefileParameterVectorDestination object at 0x000002936A594B80>}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/ooh_y/AppData/Local/Temp/processing_ANnkHD/f1df2dc403cd495d894ab74e49d5b151/output.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by JamesParrott** [comment]
PR # 13 9ee4d1b and 7e6a0d9 should fix this

**Comment by rtsaboya** [comment]
Yes, I came here to report this same issue.

As a workaround, I replaced two occurrences of `time.clock()` by `time.process_time()` in runcalculation.py and it worked.

**Comment by JamesParrott** [comment]
> As a workaround, I replaced two occurrences of `time.clock()` by `time.process_time()` in runcalculation.py and it worked.

Great stuff!

Crispin - I kept my suggested changes as simple as possible while also aiming for Python 2/3 compatibility.  But if these two above really are the only references to time.clock, then to build a Python 3 only version of sDNA, rtsaboya's changes are even simpler and safer then mine.  Mine switches the order of two imports and adds in time.clock = time.process_time to the time module namespace if time.clock raises an error.

**Comment by AnjanaaDevi-Srikanth** [comment]
> Yes, I came here to report this same issue.
> 
> As a workaround, I replaced two occurrences of `time.clock()` by `time.process_time()` in runcalculation.py and it worked.
> 
> Edit: I just noticed that, in my case, the changes were made in the non-open-source version of sDNA under QGIS 3
![Screenshot 2022-12-01 140211](https://user-images.githubusercontent.com/98437129/204978041-f5446d3d-a41f-43a6-b53f-c34848acc10e.jpg)
.

Thanks! I found the same issue with sDNA analysis today. I came here to try this, but found that I couldn't save the file (please see screenshot) - would anyone know how I can work around this? 
Unfortunately I don't have a coding background, so my knowledge of Python is rudimentary.

**Comment by JamesParrott** [comment]
@AnjanaaDevi-Srikanth I can recreate this error.  Try launching IDLE as admin from the Start Menu (right click its entry first).

**Comment by AnjanaaDevi-Srikanth** [comment]
Thanks, I will try this!
________________________________

**Comment by Pi-Garvey** [comment]
> Yes, I came here to report this same issue.
> 
> As a workaround, I replaced two occurrences of `time.clock()` by `time.process_time()` in runcalculation.py and it worked.
> 
> Edit: I just noticed that, in my case, the changes were made in the non-open-source version of sDNA under QGIS 3.

Wow! It works for me! Thank you!

**Comment by fiftysevendegreesofrad** [comment]
The new open source sdna_plus fixes this issue.
